image: ravendb/ravendb:latest
manifests:
  -
    image: ravendb/ravendb:5.1-ubuntu-latest
    platform:
      architecture: amd64
      os: linux
  -
    image: ravendb/ravendb:windows-nanoserver-latest
    platform:
      architecture: amd64
      os: windows
