name: conventions

on:
  pull_request_target

jobs:

  job1:
    name: Label
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Label
        env:
          githubOwner: ${{ github.event.pull_request.base.repo.owner.login }}
          repoName: ${{ github.event.repository.name }}
          newLabel: ${{ github.event.pull_request.base.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPlus_ReadyToRunExcludeList: 'System.Security.Cryptography.X509Certificates'
          Raven_Enable_Per_Test_Logging: 'true'
        if: contains(github.event.pull_request.labels.*.name, env.newLabel) == false
        run: ./scripts/githubActions/set_github_label.ps1 -owner ${{env.githubOwner}} -repo ${{env.repoName}} -pullRequestId ${{ github.event.pull_request.number }} -label ${{env.newLabel}}

  job2:
    name: CLA Signed
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: CLA Signed test
        env:
          CLA_SIGNED_URL: http://api.web.ravendb.net/api/v1/contributors/cla/signed?pullRequestId=
          ghprNumber: ${{ github.event.pull_request.number }}
        if: github.event.pull_request.base.repo.owner.login == 'ravendb' && github.event.repository.name == 'ravendb'
        run: ./scripts/githubActions/claSigned.ps1

  job3:
    name: Commit Conventions
    runs-on: windows-latest
    strategy:
      fail-fast: false
    env:
      githubOwner: ${{github.event.pull_request.base.repo.owner.login}}
      repoName: ${{github.event.repository.name}}
      label: ${{github.event.pull_request.base.ref}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ghprNumber: ${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v2
      - name: Commit Message Conventions
        run: ./scripts/githubActions/commitMessageConventions.ps1

      - name: Upload artifact status_message
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: pass_status_message
          path: status_message.txt

      - name: Commit Whitespace Conventions
        if: always()
        run: ./scripts/githubActions/commitWhitespaceConventions.ps1
      
      - name: Upload artifact status_whitespace
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: pass_status_whitespace
          path: status_whitespace.txt

  job4:
    if: always()
    needs: job3
    name: Generate Slack notification message
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts 1
        uses: actions/download-artifact@v1
        with:
          name: pass_status_message

      - name: Download artifacts 2
        uses: actions/download-artifact@v1
        with:
          name: pass_status_whitespace
        
      - name: Generate message
        run: ./scripts/githubActions/ConventionsGenerateMessage.sh
        env:
          PRLINK: ${{ github.event.pull_request.html_url }}
          PRTARGETBRANCH: ${{ github.event.pull_request.base.ref }}
          PRNUMBER: ${{ github.event.pull_request.number }}
          PRTITLE: ${{ github.event.pull_request.title }}
      
      - name: Upload artifact slack_message
        uses: actions/upload-artifact@v1
        with:
          name: notification
          path: notificationMessage.txt
