name: Send slack notification

on:
  workflow_run:
    workflows: [compile, conventions]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Download artifact'
        uses: actions/download-artifact@v1
        with:
          name: notification
      - name: Send notification
        run: ./scripts/githubActions/sendSlackNotification.sh
        env:
          MESSAGEPATH: notification/notificationMessage.txt
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          CHANNEL: pull-requests
